services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - user
      - product
      - order

  user:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    restart: always
    depends_on:
      - "mongodb"
    environment:
      - NODE_ENV=production

  product:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - "mongodb"
    environment:
      - NODE_ENV=production

  order:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - app-network
    depends_on:
      - "mongodb"
    environment:
      - NODE_ENV=production

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
